CREATE TABLE [dbo].[Products]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [NAME] NVARCHAR(150) NULL, 
    [IMAGE] NVARCHAR(150) NULL, 
    [PRICE] FLOAT NULL, 
    [DESCRIPTION] NVARCHAR(150) NULL, 
    [IDCAT] INT NOT NULL, 
    CONSTRAINT [FK_Products_Categories] FOREIGN KEY ([IDCAT]) REFERENCES [Categories]([ID]) 
)
